language: go
sudo: false
go:
  - 1.6
  - tip

script:
  - go get github.com/gin-gonic/gin
  - go get github.com/mattn/go-sqlite3
  - go get gopkg.in/gorp.v1
  - go test -v -covermode=count -coverprofile=coverage.out
